set nocompatible                " choose no compatibility with legacy vi
call pathogen#infect()          " Use pathogen for bundle management
let mapleader=","               " Set the best leader
syntax enable
set encoding=utf-8
set showcmd                     " display incomplete commands
filetype plugin indent on       " load file type plugins + indentation

"" Whitespace
set nowrap                      " don't wrap lines
set tabstop=2 shiftwidth=2      " a tab is two spaces 
set expandtab                   " use spaces, not tabs 
set backspace=indent,eol,start  " backspace through everything in insert mode

"" Searching
set hlsearch                    " highlight matches
set incsearch                   " incremental searching
set ignorecase                  " searches are case insensitive...
set smartcase                   " ... unless they contain at least one capital letter

"" Escaping from instert mode
inoremap jj <ESC>
inoremap kk <ESC>

"" Easie command mode entering
nnoremap ; :

