# Suport for solarized and other themes
export TERM="screen-256color"

# Initialize colors.
autoload -U colors
colors

# Autoload zsh functions.
fpath=(~/.zsh/functions $fpath)
autoload -U ~/.zsh/functions/*(:t)

. ~/.zsh/environment
. ~/.zsh/prompt
. ~/.zsh/colors
. ~/.zsh/completion
. ~/.zsh/bindings
. ~/.zsh/history

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
PATH=/usr/local/bin:$PATH # Add local to get homebrew installs first

