# Initialize colors.
autoload -U colors
colors

# Autoload zsh functions.
fpath=(~/.zsh/functions $fpath)
autoload -U ~/.zsh/functions/*(:t)

. ~/.zsh/environment
. ~/.zsh/prompt
. ~/.zsh/colors
. ~/.zsh/completion
. ~/.zsh/bindings

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
source ~/.profile

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
